services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: ${PROJECT_NAME}

    restart: unless-stopped

    environment:
      - ADMIN_TOKEN
      - DOMAIN
      - EMAIL_2FA_ENFORCE_ON_VERIFIED_INVITE
      - EMAIL_2FA_AUTO_FALLBACK
      - LOG_FILE
      - PASSWORD_HINTS_ALLOWED
      - PUSH_ENABLED
      - PUSH_INSTALLATION_ID
      - PUSH_INSTALLATION_KEY
      - REQUIRE_DEVICE_EMAIL
      - SIGNUPS_ALLOWED
      - SIGNUPS_VERIFY
      - SIGNUPS_VERIFY_RESEND_TIME
      - SIGNUPS_VERIFY_RESEND_LIMIT
      - SMTP_FROM
      - SMTP_HOST
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_SECURITY
      - YUBICO_CLIENT_ID
      - YUBICO_SECRET_KEY

    volumes:
      - ~/docker-volumes/vw-data:/data # the path before the : can be changed
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    ports:
      - ${HOST_PORT}:80

    networks:
      - homelab_net

  backup:
    image: ttionya/vaultwarden-backup:latest
    container_name: ${PROJECT_NAME}-backup
    restart: unless-stopped
    environment:
      - BACKUP_FILE_SUFFIX
      - BACKUP_KEEP_DAYS
      - CRON
      - DISPLAY_NAME
      - MAIL_SMTP_ENABLE
      - MAIL_SMTP_VARIABLES
      - MAIL_TO
      - MAIL_WHEN_SUCCESS
      - MAIL_WHEN_FAILURE
      - MAIL_FORCE_THREAD
      - PING_URL
      - PING_URL_CURL_OPTIONS
      - PING_URL_WHEN_START
      - PING_URL_WHEN_START_CURL_OPTIONS
      - PING_URL_WHEN_SUCCESS
      - PING_URL_WHEN_SUCCESS_CURL_OPTIONS
      - PING_URL_WHEN_FAILURE
      - PING_URL_WHEN_FAILURE_CURL_OPTIONS
      - RCLONE_REMOTE_NAME
      - RCLONE_REMOTE_DIR
      - RCLONE_GLOBAL_FLAG
      - TIMEZONE
      - ZIP_ENABLE
      - ZIP_PASSWORD
      - ZIP_TYPE

    volumes:
      - ~/docker-volumes/vw-data:/bitwarden/data/
      - ./rclone:/config/
#      - ./backup-service.env:/.env

    networks:
      - homelab_net

networks:
  homelab_net:
    external: true
